name: Generate Pac-Man Style Contribution Graph (Dark Mode)

on:
  schedule:
    - cron: "0 0 * * *"  # daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ allows writing 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pac-Man dark mode animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./output/pacman-dark.svg?palette=github-dark&color_snake=#FFD700&color_dots=#0033CC&background=#000000

      - name: Commit and push generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update Pac-Man dark mode graph"
          add: "output"
