name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow the bot to push files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pac-Man contribution graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./output/pacman-contribution-graph.svg?theme=pacman
            ./output/pacman-contribution-graph-dark.svg?palette=github-dark&theme=pacman

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update Pac-Man contribution graph"
          add: "output"
